// flow-typed signature: 71819e26f68b1d3871d9426eba34b084
// flow-typed version: <<STUB>>/greenlock-express_v2.1.6/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'greenlock-express'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'greenlock-express' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'greenlock-express/examples/demo' {
  declare module.exports: any;
}

declare module 'greenlock-express/examples/force-renew' {
  declare module.exports: any;
}

declare module 'greenlock-express/examples/http2' {
  declare module.exports: any;
}

declare module 'greenlock-express/examples/normal' {
  declare module.exports: any;
}

declare module 'greenlock-express/examples/remote-access' {
  declare module.exports: any;
}

declare module 'greenlock-express/examples/simple' {
  declare module.exports: any;
}

declare module 'greenlock-express/examples/spdy' {
  declare module.exports: any;
}

declare module 'greenlock-express/examples/vhost' {
  declare module.exports: any;
}

declare module 'greenlock-express/glx' {
  declare module.exports: any;
}

// Filename aliases
declare module 'greenlock-express/examples/demo.js' {
  declare module.exports: $Exports<'greenlock-express/examples/demo'>;
}
declare module 'greenlock-express/examples/force-renew.js' {
  declare module.exports: $Exports<'greenlock-express/examples/force-renew'>;
}
declare module 'greenlock-express/examples/http2.js' {
  declare module.exports: $Exports<'greenlock-express/examples/http2'>;
}
declare module 'greenlock-express/examples/normal.js' {
  declare module.exports: $Exports<'greenlock-express/examples/normal'>;
}
declare module 'greenlock-express/examples/remote-access.js' {
  declare module.exports: $Exports<'greenlock-express/examples/remote-access'>;
}
declare module 'greenlock-express/examples/simple.js' {
  declare module.exports: $Exports<'greenlock-express/examples/simple'>;
}
declare module 'greenlock-express/examples/spdy.js' {
  declare module.exports: $Exports<'greenlock-express/examples/spdy'>;
}
declare module 'greenlock-express/examples/vhost.js' {
  declare module.exports: $Exports<'greenlock-express/examples/vhost'>;
}
declare module 'greenlock-express/glx.js' {
  declare module.exports: $Exports<'greenlock-express/glx'>;
}
