name: Build, Test & Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: test
      run: |
        yarn install --pure-lockfile
        yarn test
    - name: deploy
      run: |
        ROCKETRY_PW=${ROCKETRY_PW} yarn deploy
